// export const MODIFIERS = [
//   {
//     id: "mod-coklat",
//     groupId: "grp-topping-tb",
//     name: "Topping Coklat",
//     price: 3000,
//     available: true,
//   },
//   {
//     id: "mod-keju",
//     groupId: "grp-topping-tb",
//     name: "Topping Keju",
//     price: 5000,
//     available: true,
//   },
//   {
//     id: "mod-kacang",
//     groupId: "grp-topping-tb",
//     name: "Topping Kacang",
//     price: 2000,
//     available: true,
//   },
//   {
//     id: "size-s",
//     groupId: "grp-size-kopi",
//     name: "Size S",
//     price: 0,
//     available: true,
//   },
//   {
//     id: "size-m",
//     groupId: "grp-size-kopi",
//     name: "Size M",
//     price: 5000,
//     available: true,
//   },
//   {
//     id: "size-l",
//     groupId: "grp-size-kopi",
//     name: "Size L",
//     price: 10000,
//     available: true,
//   },
//   {
//     id: "level-biasa",
//     groupId: "grp-level",
//     name: "Biasa",
//     price: 0,
//     available: true,
//   },
//   {
//     id: "level-pedas",
//     groupId: "grp-level",
//     name: "Pedas",
//     price: 0,
//     available: true,
//   },
//   {
//     id: "level-extra",
//     groupId: "grp-level",
//     name: "Extra Pedas",
//     price: 2000,
//     available: true,
//   },
// ];
